### ISSUE TITLE
hi man ，it doesn't work in sierra

### ISSUE THREAD

**Issue by aizigao** [david-cako/T430-Hackintosh#3]

**Comment by david-cako** [comment]
That's entirely possible.

I haven't tested Sierra.  I didn't feel the need to update and break everything since there aren't any new features I care about.

What errors are you getting on boot?

**Comment by aizigao** [comment]
Thank you answer,I use my files and  my Sierra works well now, but I don't use discrete NVS5400M and **mini DP** can't use , so I can't use other monitor 😭 ...
what env you  using now , 10.11.5 ?  I just need a driver  to my mini DP

**Comment by david-cako** [comment]
I'm using 10.11.6 now.  I'm using built in drivers (not NVIDIA Web Driver) and displayport works perfectly with DP to DVI and DP to VGA adapters.

Make sure if you use the discrete graphics that you have it set to _only_ discrete graphics in bios, and not the switchable graphics.  The battery impact is somewhat significant, but I'm grounded at my desk 99% of the time.

**Comment by aizigao** [comment]
en , I think I should reinstall 10.11.6

**Comment by aizigao** [comment]
I had reinstall 10.11.5 , this repo works well with NVIDIA Web Driver, nice job 👍   ( but  audio card can't driving ,I used faked layout ID from other place  )

Can you share you EFI file in 10.11.6 without NVIDIA WEB Driver , THX 😄

**Comment by david-cako** [comment]
I'm sorry, I had my two machines confused.

I just checked and the T430 is running 10.11.5.

Glad to hear you got it working though!

**Comment by aizigao** [comment]
OK thank you
